### ISSUE TITLE
Nanos unikernel?

### ISSUE THREAD

**Issue by theKAKAN** [cetic/unikernels#10]
I'm thinking that this one is not open source, but a program called [Ops](https://github.com/nanovms/ops) uses it, which is open source.  
Any plans on adding this?

**Comment by banzo** [comment]
sure, maybe you can do a PR to add that solution to the [Existing projects](https://github.com/cetic/unikernels#existing-projects) and [Comparing Solutions](https://github.com/cetic/unikernels#comparing-solutions) sections?

**Comment by theKAKAN** [comment]
Done. Pull request #11

**Comment by banzo** [comment]
Thanks! 

We also added contribution guidelines (#8)
