### ISSUE TITLE
Unik: Connection refused while trying create sample unikernel applications

### ISSUE THREAD

**Issue by GaetanLongree** [cetic/unikernels#2]
After installing and attempting to run a sample unikernel application following the [Run your first C++ unikernel guide](https://github.com/solo-io/unik/blob/master/docs/getting_started_cpp.md), launching the `unik daemon` and attempting to build any code using `unik build` returns a connection refused error:

```
ERRO[0000] build failed: [cmd/build.go:105] building image failed: {[client/images.go:60] request failed: {[lxhttpclient/httpclient.go:339] error performing post request: {Post http://localhost:3000/images/myImage/create?base=rump&lang=nodejs&provider=virtualbox&args=&mounts=&force=false&no_cleanup=false: dial tcp [::1]:3000: getsockopt: connection refused}}}
```

Furthermore, the documentation states the daemon running on port 3000, so does the `unik build` command by default. However when launching the `unik daemon`, the application states the daemon as listening on port 9967.
Changing the port of the `unik build` command yields the same error regardless.

**Comment by theKAKAN** [comment]
Please create the issue at Unik's [Github repository](https://github.com/solo-io/unik)  
This is a place for just general reference to what Unikernels are, what they do, how they are useful to us and the currently on going projects.  
It's the wrong place to ask help for a project :)

**Comment by GaetanLongree** [comment]
As mentioned in §1 of [Choice of Unikernel Solution](https://github.com/cetic/unikernels#choice-of-unikernel-solution), an issue is already present on the Unik's repository (see [issue #152](https://github.com/solo-io/unik/issues/152)). Albeit slightly different (I tested Java, the issue #152 relates to Node,js) the underlying problem is the same.

This project was my university thesis during an internship at [CETIC](https://www.cetic.be/?lang=en) and it was decided to have issues related to the thesis' progression submitted both to this repository and the concerning project's repository.

**Comment by banzo** [comment]
for clarity reasons, I'll close this issue.
