### ISSUE TITLE
MirageOS supports KVM, and even it can run on RTOS/MCU.

### ISSUE THREAD

**Issue by ehirdoy** [cetic/unikernels#5]
In this readme.md, there are some mentioning that MirageOS is supported only on KVM, but now with solo5, MirageOS can run on KVM as well. This should be updated to catch up the latest status of it.

ref:
https://mirage.io/
https://mirage.io/blog/2018-esp32-booting

**Comment by banzo** [comment]
@ehirdoy thanks for your input, we have updated the document.
