### ISSUE TITLE
Add torokernel to the comparison

### ISSUE THREAD

**Issue by MatiasVara** [cetic/unikernels#7]
It may be interesting to add torokernel to the comparison (see https://github.com/MatiasVara/torokernel).

**Comment by banzo** [comment]
sure, maybe you can do a PR to add your solution to the [Existing projects](https://github.com/cetic/unikernels#existing-projects) and [Comparing Solutions](https://github.com/cetic/unikernels#comparing-solutions) sections?

**Comment by MatiasVara** [comment]
I will do that. Thanks.
